version: '2'
services:
  yuqing:
    image: founder/mbd-web-platform:${DOCKER_TAG}
    restart: always
    mem_reservation: 2147483648
    environment:
      JVM_HEAP: 2048
      LOG_LEVEL: "${LOG_LEVEL}"
      LOG_HOME: /data/logs/yuqing
      LOG_LEVEL_STASH: "${LOG_STASH_LEVEL}"
      LOG_STASH_DESTINATION: ${LOG_STASH_DESTINATION}
      # Redis 配置
      REDIS_HOSTS: ${REDIS_HOSTS}
      REDIS_CHANNEL: web-yuqing
      APP_ACTIVE_PROFILE: yuqing
      # 开放接口
      MBD_API_HOST: ${API_PROXY_LOCAL_HOST}
      MBD_API_CONTEXT: "/api/ /mbd-cloud-"
      MBD_API_LOCAL_HOST: ${API_PROXY_LOCAL_HOST}
      MBD_API_LOCAL_CONTEXT: "/api/ /mbd-cloud-"
      # 平台配置
      MBD_WEB_ID: 2
      MBD_WEB_CODE: yuqing
      MBD_WEB_NAME: 智思舆情
      MBD_WEB_VERSION: 1.0.0
      MBD_WEB_THEME: founder
      MBD_WEB_PAGE_LOGIN: /login
      MBD_WEB_PAGE_HOME: /yuqing/home
    volumes:
      - logs_root:/data/logs
    labels:
      io.rancher.container.hostname_override: 'container_name'
      io.rancher.container.pull_image: always
      io.fzyun.service.refcom: founder/openjdk
      io.fzyun.service.username: rengy
      traefik.enable: 'true'
      traefik.frontend.entryPoints: http,https
      traefik.port: '8080'
      {{- if (.Values.HOST_YUQING)}}
      traefik.frontend.rule: 'Host:${HOST_YUQING}'
      {{- end}}
      traefik.frontend.headers.SSLRedirect: '${FORCE_SSL}'
    logging:
      options:
        max-size: "50m"
        max-file: "10"
volumes:
  logs_root:
    driver: rancher-nfs
  attachment-root:
    driver: rancher-nfs